louvres_ticketing_homepage:
    path:     /
    defaults: { _controller: LouvresTicketingBundle:Home:index }

louvres_ticketing_prices:
    path:     /tarifs
    defaults: { _controller: LouvresTicketingBundle:Prices:prices }

louvres_ticketing_booking:
    path:     /billetterie
    defaults: { _controller: LouvresTicketingBundle:Ticketing:index }
    requirements:
        id: \d+

louvres_ticketing_visitor:
    path:     /billetterie/{nbVisitor}
    defaults: { _controller: LouvresTicketingBundle:Visitor:index }
    requirements:
        nbVisitor: \d+

louvres_ticketing_order:
    path:     /commande
    defaults: { _controller: LouvresTicketingBundle:Order:index }

louvres_ticketing_payment:
    path:     /paiement
    defaults: { _controller: LouvresTicketingBundle:Order:payment }

