louvres_ticketing_homepage:
    path:     /
    defaults: { _controller: LouvresTicketingBundle:Home:index }

louvres_ticketing_prices:
    path:     /tarifs
    defaults: { _controller: LouvresTicketingBundle:Prices:prices }

louvres_ticketing_booking:
    path:     /billetterie
    defaults: { _controller: LouvresTicketingBundle:Ticketing:index }

louvres_ticketing_visitor:
    path:     /billetterie2
    defaults: { _controller: LouvresTicketingBundle:Visitor:index }

louvres_ticketing_order:
    path:     /commande
    defaults: { _controller: LouvresTicketingBundle:Order:index }

louvres_ticketing_credits:
    path:     /credits
    defaults: { _controller: LouvresTicketingBundle:Credits:index }

louvres_ticketing_contact:
    path:     /contact
    defaults: { _controller: LouvresTicketingBundle:Contact:send }
