louvres_ticketing_homepage:
    path:     /
    defaults: { _controller: LouvresTicketingBundle:Home:index }

louvres_ticketing_prices:
    path:     /tarifs
    defaults: { _controller: LouvresTicketingBundle:Prices:prices }

louvres_ticketing_ticketing:
    path:     /billetterie
    defaults: { _controller: LouvresTicketingBundle:Ticketing:index }
